### ISSUE TITLE
/user/twitter　にアクセスした際にトップページに遷移してしまう

### ISSUE THREAD

**Issue by gonkunkun** [perches-team/shubun_doc#58]
/user/twitter　にアクセスした際には、
twitter認証処理に遷移するはずであるが、トップページに自動的に遷移してしまい
twitter認証処理に辿り着くことができない。

**Comment by gonkunkun** [comment]
feature/twitter-token-authブランチにマージリクエストと同時に対応が必要になるかと思います

**Comment by tachibanayu24** [comment]
/user/twitterはnginxでなにもしない　-> not foundに遷移する
